name: Native Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'zulu' }
      - name: Build with Gradle
        run: |
          chmod +x gradlew || (echo "Creating wrapper" && gradle wrapper)
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/BT-NATIVE-PRO.apk
      - uses: actions/upload-artifact@v4
        with: { name: BT-NATIVE-PRO, path: app/build/outputs/apk/debug/BT-NATIVE-PRO.apk }